services:
  - type: web
    name: transitops-sumo
    runtime: docker
    plan: free
    region: virginia
    dockerfilePath: ./simulation/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: SUMO_END
        value: "900"
